# Change these first
owner: pinnode # Your GitHub organization or username, where this repository lives
repo: pinnode # The name of this repository

sites:
  - name: 제주 4.3
    url: http://43archives.or.kr/main.do
  - name: 이뮤지엄
    url: https://www.emuseum.go.kr/main
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pinnode.github.io/pinnode
  #baseUrl: /pinnode
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: pinnode
  introTitle: "Pinnode server manager"
  introMessage: pinnode
  navbar:
    
    - title: Pinnode
      href: https://pinnode.github.io/pinnode

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
