# Change these first
owner: pinnode # Your GitHub organization or username, where this repository lives
repo: pinnode # The name of this repository

sites:
  - name: jeju 4.3
    url: http://43archives.or.kr/main.do
  - name: emusium
    url: https://www.emuseum.go.kr/main
  - name: jp
    url: https://archives.jp.go.kr/
  - name: jp - admin
    url: https://archives.jp.go.kr/admin
  - name: ggmemory
    url: https://memory.library.kr/main
  - name: ggmemory - admin
    url: https://memorysuper.library.kr/
  - name: hangeul
    url: https://archives.hangeul.go.kr/  
  - name: hangeul - cms
    url: http://mms.hangeul.go.kr:9001/login
  - name: hangeul - mms
    url: http://mms.hangeul.go.kr:9002/login
  - name: Kculture
    url: http://www.kcultureroad.kr/
  - name: Kculture - admin
    url: http://www.kcultureroad.kr/login

    
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: pinnode.github.io/pinnode
  #baseUrl: /pinnode
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: pinnode
  introTitle: "Pinnode server manager"
  introMessage: pinnode
  navbar:
    
    - title: Pinnode
      href: https://pinnode.github.io/pinnode

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
